# Generated by Django 3.2.1 on 2021-06-29 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='date',
        ),
        migrations.AddField(
            model_name='patient',
            name='birth_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
