# Generated by Django 3.2.1 on 2021-06-29 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0002_auto_20210629_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.BigIntegerField(null=True),
        ),
    ]
