# Generated by Django 3.2.1 on 2021-07-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0003_auto_20210629_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='age',
        ),
        migrations.AddField(
            model_name='patient',
            name='bdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
