# Generated by Django 3.2.1 on 2021-08-16 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0008_auto_20210816_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='advice',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='complication',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='diagnosis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='due',
            field=models.CharField(default=0, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='dueLength',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='history',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientName', models.CharField(max_length=200, null=True)),
                ('date', models.DateTimeField(null=True)),
                ('var1', models.IntegerField(default=0, null=True)),
                ('var2', models.IntegerField(default=0, null=True)),
                ('var3', models.IntegerField(default=0, null=True)),
                ('schedule', models.CharField(max_length=200, null=True)),
                ('var4', models.IntegerField(default=0, null=True)),
                ('due', models.CharField(max_length=200, null=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login_signup.doctor')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login_signup.patient')),
                ('prescription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login_signup.prescription')),
            ],
        ),
    ]
