# Generated by Django 3.2.1 on 2021-08-16 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0009_auto_20210816_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientName', models.CharField(max_length=200, null=True)),
                ('date', models.DateTimeField(null=True)),
                ('medicine', models.CharField(max_length=200, null=True)),
                ('var1', models.IntegerField(default=0, null=True)),
                ('var2', models.IntegerField(default=0, null=True)),
                ('var3', models.IntegerField(default=0, null=True)),
                ('schedule', models.CharField(max_length=200, null=True)),
                ('var4', models.IntegerField(default=0, null=True)),
                ('due', models.CharField(max_length=200, null=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login_signup.doctor')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login_signup.patient')),
                ('prescription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login_signup.prescription')),
            ],
        ),
        migrations.DeleteModel(
            name='Medicine',
        ),
    ]
