# Generated by Django 3.2.1 on 2021-08-17 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0010_auto_20210816_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='gender',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
